version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "5000:5000"
    volumes:
      - ./api:/var/www/api
      - ./client:/var/www/client