version: '3'

services:
  rms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8123:80"
    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/html
      - ./client:/var/www/client