#!/usr/bin/env bash

manage-node &

DB_FILE=database/database.sqlite

if [ ! -f "$DB_FILE" ]; then
    echo "[+] $DB_FILE does not exist."
    echo "[+] creating"
    touch database/database.sqlite
fi

ENV_FILE=.env
if [ ! -f "$ENV_FILE" ]; then
    echo "[+] $ENV_FILE does not exist."
    echo "[+] Copying .env"
    cp .env.example .env
fi

echo "[+] Running php artisan migrate --seed"
php artisan migrate --seed

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
